name: CI-RS

on:
  push:
    paths:
      - "**/src/**"
      - "**/Cargo.lock"
      - "**/Cargo.toml"
      - "**/rust-toolchain"
      - "**/.taplo.toml"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  CARGO_TERM_VERBOSE: true
  RUST_BACKTRACE: 1


jobs:
  ci-rs:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-14 ]
        rust-toolchain:
          - nightly

    runs-on: ${{ matrix.os }}

    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Setup ${{ matrix.rust-toolchain }} rust toolchain with caching
        uses: brndnmtthws/rust-action@v1
        with:
          toolchain: ${{ matrix.rust-toolchain }}
          components: rustfmt, clippy
          enable-sccache: "true"

      - name: Install binaries
        run: sudo apt-get update && sudo apt-get install -y clang pkg-config libavfilter-dev libavdevice-dev libavcodec-dev libavformat-dev libavutil-dev

      - name: Build
        run: cargo build --release

      - name: Test
        run: cargo test --release

      - name: Lint
        run: cargo clippy
      
      - name: Check Formatting
        run: cargo fmt --all -- --check
